### ISSUE TITLE
Big logo

### ISSUE THREAD

**Issue by narbuvold** [holmgr/gamejam#1]
The logo is so big you don't see that the page contains anything else. A hint of text would be prefered.

**Comment by holmgr** [comment]
Understand the problem but in reality it is quite hard to guarantee as the viewport size is different for almost every device. On what device did you observe this? It would be helpful to know so I can replicate more easily

**Comment by narbuvold** [comment]
On a mac
![screen shot 2016-04-14 at 19 10 17](https://cloud.githubusercontent.com/assets/11999298/14536846/b317b3dc-0274-11e6-9327-79b43b15ff67.png)

**Comment by holmgr** [comment]
Oh I see. Well this might be a bigger problem then I first thought because gets into some of the particularities of svg images. Hopefully I can fix it this weekend
