### ISSUE TITLE
Link to Olivia de Flon links to http://holmgr.github.io/gamejam/

### ISSUE THREAD

**Issue by david-bergstrom** [holmgr/gamejam#6]
The link could be replaced with a link to her LinkedIn or Twitter.

**Comment by holmgr** [comment]
I.e exactly what I asked for in issue #2. Is https://twitter.com/oliviadeflon the correct Twitter link?

**Comment by holmgr** [comment]
Seeing that I have not gotten any response, I will assume that the link is correct.
